### ISSUE TITLE
Module Not Found: gdal

### ISSUE THREAD

**Issue by esnyder-rve** [EarthObservation/rvt-qgis#10]
With the new OSGeo4W installer, it appears that the python gdal library got changed. The plugin can no longer load with this error in default.py: ModuleNotFoundError: No module named 'gdal'

Can be fixed by changing `import gdal` with `from osgeo import gdal`

**Comment by zm8597** [comment]
I applied your fix and uploaded a new version of the plugin v0.5.2. Could you please check if the problem is solved? Thank you for your issue report and help 😃.
