### ISSUE TITLE
Error module on startup QGIS

### ISSUE THREAD

**Issue by bellanz80** [EarthObservation/rvt-qgis#14]
Hello, I have installed version 0.7 of the RVT plug.
Both in windows 10 and in ubuntu 20.10., Same version of QGIS 3.18.3.
But, while in ubuntu I don't have any error, in windows 10 when loading QGIS a python module error appears and it does not load the plug.
Capture Annex

Couldn't load plugin 'rvt-qgis' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'processing_provider.provider' 
Traceback (most recent call last):
  File "C:/OSGeo4W/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\ULTIMO 3.16/python/plugins\rvt-qgis\__init__.py", line 35, in classFactory
    from .qrvt import QRVT
  File "C:/OSGeo4W/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\ULTIMO 3.16/python/plugins\rvt-qgis\qrvt.py", line 65, in 
    from processing_provider.provider import Provider
  File "C:/OSGeo4W/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'processing_provider.provider'

Python version: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] 
QGIS version: 3.18.3-Zürich Zürich, 735cc85be9 

Python Path:
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\ULTIMO 3.16/python/plugins\road_slope_calculator
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\ULTIMO 3.16/python/plugins\open_lidar_tools
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\ULTIMO 3.16/python/plugins\MultiMaps
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\ULTIMO 3.16/python/plugins\lftools
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\ULTIMO 3.16/python/plugins\LAStools
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\ULTIMO 3.16/python/plugins\HTML_Generator-main
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\ULTIMO 3.16/python/plugins\clusterpoints
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\ULTIMO 3.16/python/plugins\Cadastral_Divisions-main
C:/OSGeo4W/apps/qgis/./python
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\ULTIMO 3.16/python
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\ULTIMO 3.16/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python39.zip

**Comment by zm8597** [comment]
Hi, I can't recreate your bug. To me it seems like there is a missing path to RVT plugin directory (under Python Path). You have 2 installation of QGIS 3.16 and 3.18 as I can see QGIS 3.18 is calling profile paths from QGIS 3.16. There is missing a path like "C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\ULTIMO 3.16/python/plugins\rvt-qgis" or presumably "C:/OSGeo4W/apps/qgis/./python/plugins\rvt-qgis". Try adding one of the paths to enviroment variables (Oprions, System, Enviroment, Use custom variables, Add Variable "PATH" and under Value one of the paths) or try resinstalling QGIS.

**Comment by bellanz80** [comment]
Very thank`s! y chek this!
