### ISSUE TITLE
Revert loading into QGIS

### ISSUE THREAD

**Issue by czalaviek** [EarthObservation/rvt-qgis#18]
I was unable to load plugin after upgrading to v 0.9.3. The reason is not well defined paths to Your module "processing". I prepared new Pull with my "pill" to repair it. My QGIS is 3.26. Pull:[https://github.com/EarthObservation/rvt-qgis/pull/17](url)

**Comment by zm8597** [comment]
I merged your PR and released a new version of the plugin, can you check if the issue got fixed? Thank you for your contribution :).

**Comment by czalaviek** [comment]
Everything works well, now. Thx
