### ISSUE TITLE
RVT Plug-in 

### ISSUE THREAD

**Issue by Chippy1635** [EarthObservation/rvt-qgis#20]
I am relatively new to QGIS. I cannot see what I need to do to get the RVT plug-in to allow me to add input files. Only already saved files are available to select for visualisation changes. Attached is screen shot of the display. The RVT stand-alone version allows selection of new input files. 

I am using QGIS Desktop3.34.1 on a Windows 11 PC. I have tried re-installing the stable release version QGIS Desktop 3.28.14 but the same issue arises.

What am I doing wrong?!

[RVT Issue in QGIS.docx](https://github.com/EarthObservation/rvt-qgis/files/13891973/RVT.Issue.in.QGIS.docx)

**Comment by zkokalj** [comment]
Hi! You can open all of the single band files that are added to the current QGIS project, but you cannot yet open files directly from disk.

**Comment by zkokalj** [comment]
Hi! You can open all of the single band files that are added to the current QGIS project, but you cannot yet open files directly from disk.

**Comment by Chippy1635** [comment]
Thanks very much for the advice.
