### ISSUE TITLE
How do I modify the default parameters in qgis

### ISSUE THREAD

**Issue by ZW000506** [EarthObservation/rvt-qgis#21]
When I use the RVT plug-in in qgis, the default search radius of the openness toolbar is calculated to be 10-50 pixels, I want to have more options, how can I modify it
![e05d70df7ef9a3bfb2a88036eb1e7ed5](https://github.com/EarthObservation/rvt-qgis/assets/111566093/7d971a7b-0d9b-44a5-96b0-f77d60908856)

**Comment by zkokalj** [comment]
Hi!
On windows, you can modify all the parameters in Python scrips saved in 
c:\Users\USERNAME\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\rvt-qgis\processing_provider\
What you are looking for is in file rvt_opns.py, line 98.

**Comment by ZW000506** [comment]
So I would like to ask what is the unit of radius,If it is meters, do my DEM data need to be projected If it is simply pixel size, DEM data does not need to be projected？

**Comment by NejcCoz** [comment]
Hi.

You are absolutely right — the radius is specified in pixels. All processing in RVT is done on a pixel basis, so the projection of your DEM data has no effect on the results.
