### ISSUE TITLE
Can't resize plugin window

### ISSUE THREAD

**Issue by TechGus** [EarthObservation/rvt-qgis#6]
The plugin window is too tall and doesn't fit on the screen and the OK button is not visible. There are no scroll bars and when trying to resize it, it disappears and can't be restored in any possible way. The only solution is to right-click on the taskbar and click "close window" to close the plugin window. So far, I wasn't able to use the plugin because of this.

**Comment by zm8597** [comment]
Hello thank you for your bug report. Can you please provide me your screen resolution, dpi settings and QGIS version?

**Comment by TechGus** [comment]
Sorry for not including the info in the original message, but here goes:
Windows 10
QGIS 3.16.2
Resolution 1366 x 768
Scaling: 100%

**Comment by zm8597** [comment]
Currently we don't support resolutions bellow 1920x1080. We have a plan to implement a few new visualizations after that we will make GUI that will support lower resolutions.

**Comment by TechGus** [comment]
Ok, thanks. Will check back to see when that happens!

**Comment by zm8597** [comment]
Hello @TechGus. I fixed plugin GUI, by applying scrollbars. Let me know if anything doesn't work.

**Comment by TechGus** [comment]
@zm8597 It's working great now!
