### ISSUE TITLE
AttributeError: 'DefaultValues' object has no attribute 'msrm_compute' 

### ISSUE THREAD

**Issue by abdulhafidz6** [EarthObservation/rvt-qgis#7]
Hi, I just upgraded my plugin to 0.3.4 and couldn't load the plugin. Thank you in advance.

Couldn't load plugin 'rvt-qgis' due to an error when calling its classFactory() method 

AttributeError: 'DefaultValues' object has no attribute 'msrm_compute' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rvt-qgis\__init__.py", line 36, in classFactory
    return QRVT(iface)
  File "C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rvt-qgis\qrvt.py", line 213, in __init__
    self.load_default2dlg()  # load values in dialog
  File "C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rvt-qgis\qrvt.py", line 878, in load_default2dlg
    self.dlg.group_multi_relief.setChecked(bool(self.default.msrm_compute))
AttributeError: 'DefaultValues' object has no attribute 'msrm_compute'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.3-Hannover Hannover, 94ac9f21b8 

Python Path:
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\network_gt
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geometric_attributes
C:/OSGEO4~1/apps/qgis/./python
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\Users\hp\AppData\Roaming\Python\Python37\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\hp\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\GeoTrace\tools
C:\Users\hp\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QSWATPlus3_64

**Comment by zm8597** [comment]
Hello. When you update plugin you have to restart QGIS. Sometimes we update core library and core library (rvt_py) is not refreshed on update (only plugin code is), core library is loaded only when you start QGIS. Let me know if restarting QGIS solved the problem or problem still occurs? 😃

**Comment by abdulhafidz6** [comment]
Hi, I just check it and it is in my Raster menu now. thank you for your response. I do love your works.. 👍🏻👍🏻

**Comment by zm8597** [comment]
Thank you for your kind words.😄

**Comment by zm8597** [comment]
Bug was resolved in plugin version 0.4.0, now plugin refreshes rvt-py library when you update plugin.
