### ISSUE TITLE
Error Qt::AA_EnableHighDpiScaling

### ISSUE THREAD

**Issue by bellanz80** [EarthObservation/rvt-qgis#8]
Hi. I-m Luca from Mexico.
I am a great admirer of your work, I have been using the ReliefVisualization tool for 4 years, in field analysis for archaeological inspection. Thank you very much for your beautiful work.

Now I have a crash problem of QGIS 3.16.3 on Ubuntu 20.04.
The program opens and closes, and the console returns this error:

luca@pop-os:~$ qgis --profile 3.16
Warning: Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
![Selection_007](https://user-images.githubusercontent.com/38449926/106393440-b8c74280-63bc-11eb-9bec-3169f5c0b90b.png)

I have created a new profile, without plugins.
And I have tried to install the plugins that I use, one by one, observing the console.

The result is that when you install ReliefVisualizatinTool, this message appears, and the crash problems start.
The crashes do not always appear, that is, they appear random, but sometimes I have to restart the program 4 or 5 times, so that it works correctly.

I have already activated the HiDPI mode of the system but something of the plug creates the conflict.
My monitor is 2K Ultra Wide (3440 * 1440 pixel)
![Error QGIS](https://user-images.githubusercontent.com/38449926/106393532-41de7980-63bd-11eb-8a9d-9e2a8a7973f1.png)
In fact, when activating the plug, the window stretches a lot.
![Selection_008](https://user-images.githubusercontent.com/38449926/106393554-5de21b00-63bd-11eb-9b0e-0d767b4018d1.png)

I hope with my test, it helps.
A cordial greeting

**Comment by zm8597** [comment]
Hi Luca, thak you for your kind words and well documented bug. We appriciate your support.

I just uploaded version 0.4.0 where bug should be resolved. I was enabling high DPI scaling in plugin but QGIS already enables it. I removed that part of code. I also implemented that plugin saves its size when pressing start or blend and loads this size when you start QGIS. Now every user can set its own plugin size. Can you check if this bug still occurs (in new version 0.4.0)?

**Comment by bellanz80** [comment]
Hi! 
I just tested it on windows and linux, and everything seems to work fine!
Thanks for the support !
